deeplake:
  token: "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpZCI6InN1cHJpeWEwMiIsImFwaV9rZXkiOiJiTTZubE5wTzd6cjNlR21HYVVKaW5DbkFQRzVTbTZrbi0wQlk2bDU1VjdZNnkifQ."
  dataset_path: "hub://supriya02/ams-docs"
huggingface:
  token: "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"
groq:
  api_key: "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"
langsmith:
  LANGCHAIN_TRACING_V2: 'true'
  LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
  LANGCHAIN_API_KEY: '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'
  LANGCHAIN_PROJECT: "ams-demo-main"
azure_search:
  endpoint: "https://ams-knowledgebase.search.windows.net"
  key: "mcpN5sQjMdY8B4uNL8Bip9sYviOQ0acpcFeig7OF3iAzSeAEMSUj"
  index_name: "documents"

flask:
  secret_key: "194ac69c402b7dd989110d4ba2553398"