deeplake:
  token: "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpZCI6InN1cHJpeWEwMiIsImFwaV9rZXkiOiJiTTZubE5wTzd6cjNlR21HYVVKaW5DbkFQRzVTbTZrbi0wQlk2bDU1VjdZNnkifQ."
  dataset_path: "hub://supriya02/ams-docs"
huggingface:
  token: "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"
groq:
  api_key: "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"